export const countryNames: Record<string, string> = {
  'FR': 'France',
  'US': 'United States',
  'GB': 'United Kingdom',
  'CA': 'Canada',
  'AU': 'Australia',
  'DE': 'Germany',
  'IT': 'Italy',
  'ES': 'Spain',
  'JP': 'Japan',
  'CN': 'China',
  'IN': 'India',
  'BR': 'Brazil',
  'RU': 'Russia',
  'ZA': 'South Africa',
  'MX': 'Mexico',
  'AR': 'Argentina',
  'CL': 'Chile',
  'CO': 'Colombia',
  'PE': 'Peru',
  'VE': 'Venezuela',
  'EC': 'Ecuador',
  'BO': 'Bolivia',
  'PY': 'Paraguay',
  'UY': 'Uruguay',
  'CR': 'Costa Rica',
  'PA': 'Panama',
  'DO': 'Dominican Republic',
  'PR': 'Puerto Rico',
  'GT': 'Guatemala',
  'HN': 'Honduras',
  'NI': 'Nicaragua',
  'SV': 'El Salvador',
  'CU': 'Cuba',
  'HT': 'Haiti',
  'JM': 'Jamaica',
  'BS': 'Bahamas',
  'TT': 'Trinidad and Tobago',
  'BB': 'Barbados',
  'GD': 'Grenada',
  'LC': 'Saint Lucia',
  'VC': 'Saint Vincent and the Grenadines',
  'AG': 'Antigua and Barbuda',
  'DM': 'Dominica',
  'KN': 'Saint Kitts and Nevis',
  'BZ': 'Belize',
  'GY': 'Guyana',
  'SR': 'Suriname',
  'GF': 'French Guiana',
  'FK': 'Falkland Islands',
  'GS': 'South Georgia and the South Sandwich Islands',
  'AI': 'Anguilla',
  'AW': 'Aruba',
  'BM': 'Bermuda',
  'VG': 'British Virgin Islands',
  'KY': 'Cayman Islands',
  'MQ': 'Martinique',
  'MS': 'Montserrat',
  'AN': 'Netherlands Antilles',
  'TC': 'Turks and Caicos Islands',
  'VI': 'U.S. Virgin Islands',
  'GP': 'Guadeloupe',
  'GL': 'Greenland',
  'PM': 'Saint Pierre and Miquelon',
  'BL': 'Saint Barthelemy',
  'MF': 'Saint Martin',
  'SX': 'Sint Maarten',
  'CW': 'Curacao',
  'BQ': 'Bonaire, Sint Eustatius and Saba',
  'WF': 'Wallis and Futuna',
  'PF': 'French Polynesia',
  'NC': 'New Caledonia',
  'TK': 'Tokelau',
  'NU': 'Niue',
  'CK': 'Cook Islands',
  'WS': 'Samoa',
  'AS': 'American Samoa',
  'GU': 'Guam',
  'MP': 'Northern Mariana Islands',
  'PW': 'Palau',
  'FM': 'Micronesia',
  'MH': 'Marshall Islands',
  'KI': 'Kiribati',
  'TV': 'Tuvalu',
  'NR': 'Nauru',
  'VU': 'Vanuatu',
  'FJ': 'Fiji',
  'TO': 'Tonga',
  'SB': 'Solomon Islands',
  'PG': 'Papua New Guinea',
  'ID': 'Indonesia',
  'MY': 'Malaysia',
  'SG': 'Singapore',
  'TH': 'Thailand',
  'VN': 'Vietnam',
  'PH': 'Philippines',
  'MM': 'Myanmar',
  'LA': 'Laos',
  'KH': 'Cambodia',
  'BN': 'Brunei',
  'TL': 'Timor-Leste',
  'NP': 'Nepal',
  'BT': 'Bhutan',
  'BD': 'Bangladesh',
  'LK': 'Sri Lanka',
  'MV': 'Maldives',
  'PK': 'Pakistan',
  'AF': 'Afghanistan',
  'IR': 'Iran',
  'IQ': 'Iraq',
  'SY': 'Syria',
  'LB': 'Lebanon',
  'JO': 'Jordan',
  'IL': 'Israel',
  'PS': 'Palestine',
  'SA': 'Saudi Arabia',
  'YE': 'Yemen',
  'OM': 'Oman',
  'AE': 'United Arab Emirates',
  'QA': 'Qatar',
  'BH': 'Bahrain',
  'KW': 'Kuwait',
  'TR': 'Turkey',
  'CY': 'Cyprus',
  'AZ': 'Azerbaijan',
  'GE': 'Georgia',
  'AM': 'Armenia',
  'KG': 'Kyrgyzstan',
  'TJ': 'Tajikistan',
  'UZ': 'Uzbekistan',
  'TM': 'Turkmenistan',
  'KZ': 'Kazakhstan',
  'MN': 'Mongolia',
  'KP': 'North Korea',
  'KR': 'South Korea',
  'TW': 'Taiwan',
  'HK': 'Hong Kong',
  'MO': 'Macau',
};

export const domainNames: Record<string, string> = {
  'com': 'Commercial',
  'org': 'Organization',
  'net': 'Network',
  'edu': 'Education',
  'gov': 'Government',
  'mil': 'Military',
  'int': 'International',
  'biz': 'Business',
  'info': 'Information',
  'name': 'Personal',
  'pro': 'Professional',
  'coop': 'Cooperative',
  'aero': 'Aviation',
  'museum': 'Museum',
  'travel': 'Travel',
  'jobs': 'Jobs',
  'mobi': 'Mobile',
  'tel': 'Telephone',
  'asia': 'Asia',
  'cat': 'Catalan',
  'co': 'Colombia',
  'io': 'British Indian Ocean Territory',
  'me': 'Montenegro',
  'tv': 'Tuvalu',
  'ws': 'Samoa',
  'fm': 'Micronesia',
  'to': 'Tonga',
  'cc': 'Cocos Islands',
  'sh': 'Saint Helena',
  'ac': 'Ascension Island',
  'im': 'Isle of Man',
  'gg': 'Guernsey',
  'je': 'Jersey',
  'eu': 'European Union',
  'uk': 'United Kingdom',
  'us': 'United States',
  'ca': 'Canada',
  'au': 'Australia',
  'nz': 'New Zealand',
  'in': 'India',
  'jp': 'Japan',
  'cn': 'China',
  'ru': 'Russia',
  'br': 'Brazil',
  'mx': 'Mexico',
  'ar': 'Argentina',
  'cl': 'Chile',
  'co': 'Colombia',
  'pe': 'Peru',
  've': 'Venezuela',
  'ec': 'Ecuador',
  'bo': 'Bolivia',
  'py': 'Paraguay',
  'uy': 'Uruguay',
  'cr': 'Costa Rica',
  'pa': 'Panama',
  'do': 'Dominican Republic',
  'pr': 'Puerto Rico',
  'gt': 'Guatemala',
  'hn': 'Honduras',
  'ni': 'Nicaragua',
  'sv': 'El Salvador',
  'cu': 'Cuba',
  'ht': 'Haiti',
  'jm': 'Jamaica',
  'bs': 'Bahamas',
  'tt': 'Trinidad and Tobago',
  'bb': 'Barbados',
  'gd': 'Grenada',
  'lc': 'Saint Lucia',
  'vc': 'Saint Vincent and the Grenadines',
  'ag': 'Antigua and Barbuda',
  'dm': 'Dominica',
  'kn': 'Saint Kitts and Nevis',
  'bz': 'Belize',
  'gy': 'Guyana',
  'sr': 'Suriname',
  'gf': 'French Guiana',
  'fk': 'Falkland Islands',
  'gs': 'South Georgia and the South Sandwich Islands',
  'ai': 'Anguilla',
  'aw': 'Aruba',
  'bm': 'Bermuda',
  'vg': 'British Virgin Islands',
  'ky': 'Cayman Islands',
  'mq': 'Martinique',
  'ms': 'Montserrat',
  'an': 'Netherlands Antilles',
  'tc': 'Turks and Caicos Islands',
  'vi': 'U.S. Virgin Islands',
  'gp': 'Guadeloupe',
  'gl': 'Greenland',
  'pm': 'Saint Pierre and Miquelon',
  'bl': 'Saint Barthelemy',
  'mf': 'Saint Martin',
  'sx': 'Sint Maarten',
  'cw': 'Curacao',
  'bq': 'Bonaire, Sint Eustatius and Saba',
  'wf': 'Wallis and Futuna',
  'pf': 'French Polynesia',
  'nc': 'New Caledonia',
  'tk': 'Tokelau',
  'nu': 'Niue',
  'ck': 'Cook Islands',
  'ws': 'Samoa',
  'as': 'American Samoa',
  'gu': 'Guam',
  'mp': 'Northern Mariana Islands',
  'pw': 'Palau',
  'fm': 'Micronesia',
  'mh': 'Marshall Islands',
  'ki': 'Kiribati',
  'tv': 'Tuvalu',
  'nr': 'Nauru',
  'vu': 'Vanuatu',
  'fj': 'Fiji',
  'to': 'Tonga',
  'sb': 'Solomon Islands',
  'pg': 'Papua New Guinea',
  'id': 'Indonesia',
  'my': 'Malaysia',
  'sg': 'Singapore',
  'th': 'Thailand',
  'vn': 'Vietnam',
  'ph': 'Philippines',
  'mm': 'Myanmar',
  'la': 'Laos',
  'kh': 'Cambodia',
  'bn': 'Brunei',
  'tl': 'Timor-Leste',
  'np': 'Nepal',
  'bt': 'Bhutan',
  'bd': 'Bangladesh',
  'lk': 'Sri Lanka',
  'mv': 'Maldives',
  'pk': 'Pakistan',
  'af': 'Afghanistan',
  'ir': 'Iran',
  'iq': 'Iraq',
  'sy': 'Syria',
  'lb': 'Lebanon',
  'jo': 'Jordan',
  'il': 'Israel',
  'ps': 'Palestine',
  'sa': 'Saudi Arabia',
  'ye': 'Yemen',
  'om': 'Oman',
  'ae': 'United Arab Emirates',
  'qa': 'Qatar',
  'bh': 'Bahrain',
  'kw': 'Kuwait',
  'tr': 'Turkey',
  'cy': 'Cyprus',
  'az': 'Azerbaijan',
  'ge': 'Georgia',
  'am': 'Armenia',
  'kg': 'Kyrgyzstan',
  'tj': 'Tajikistan',
  'uz': 'Uzbekistan',
  'tm': 'Turkmenistan',
  'kz': 'Kazakhstan',
  'mn': 'Mongolia',
  'kp': 'North Korea',
  'kr': 'South Korea',
  'tw': 'Taiwan',
  'hk': 'Hong Kong',
  'mo': 'Macau',
}; 