name: app

on:
  push:
    paths:
      - ".github/workflows/app.yml"
      - "app/**"
      - "package.json"
  pull_request:
    branches:
      - main
    paths:
      - "app/**"

jobs:
  check-app:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install yarn
        uses: yarn/action-setup@v4

      - name: Get yarn store directory
        id: yarn-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(yarn store path)" >> $GITHUB_OUTPUT

      - name: Setup yarn cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-

      - name: Install Dependencies
        run: |
          if [ -f "apps/app/yarn-lock.yaml" ]; then
            yarn install --frozen-lockfile
          else
            yarn install
          fi

#      - name: Prettier Format Check
#        run: yarn format:check
#
#      - name: Lint
#        run: yarn lint
#
      # - name: TypeScript Check
      #   run: yarn ts:check

      - name: Build
        run: yarn build
